source 'https://github.com/CocoaPods/Specs.git'
target 'NirjaraAp'
platform :ios, '9.0'

pod 'paper-onboarding', '~> 4.0'
pod 'ImageSlideshow', '~> 1.5'
pod 'SDWebImage'
pod 'ImageSlideshow/Alamofire'
pod 'Font-Awesome-Swift', '~> 1.7.2'
pod 'SwiftSVG', '~> 2.0'
pod 'Toast-Swift', '~> 3.0.1'
pod 'YouTubePlayer', '~> 0.4'
pod 'DropDown', '~> 2.3'
pod 'DatePickerDialog', '~> 2.0'
pod 'M13Checkbox', '~> 3.2'
pod 'CVCalendar', '~> 1.6'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'JHTAlertController'
pod 'SearchTextField'
pod 'SwiftyOnboard'
pod 'FSCalendar'
pod 'SMSegmentView', '~> 1.3.1'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Instamojo', :git => 'https://github.com/Instamojo/ios-sdk.git', :tag => '1.0.12'
pod 'InstaMojoiOS', '0.0.3'
pod 'FMDB'
pod 'YPImagePicker'
pod 'KKStatusBarService'
pod 'IQKeyboardManagerSwift'

use_frameworks!
